/oak1:
  ros__parameters:
    driver:
      i_ip: "10.95.76.11"
      i_enable_ir: true

    pipeline_gen:
      i_pipeline_type: RGBD
      i_nn_type: none

    rgb:
      i_fps: 15.0
      i_low_bandwidth: true

    left:
      i_low_bandwidth: true

    right:
      i_low_bandwidth: true

    stereo:
      i_fps: 15.0
      i_low_bandwidth: true
